#!/bin/bash

version() {
    echo `node -e 'console.log(require("./package.json").version)'`
}

publish() {
    npm adduser
    build
    npm publish --access public
}

build() {
    lint
    npm pack
    mkdir -p builds
    mv *.tgz builds/
}

lint() {
    node_modules/.bin/eslint '*.js'
}

case $1 in
    version )  version
               ;;

    lint )     lint
               ;;

    build )    build
               ;;

    publish )  publish
               ;;

    clean )    rm -f *.tgz
               ;;

    * )        ;;
esac
